### ISSUE TITLE
Создать схему базы данных для хранения информации о преподавателях

### ISSUE THREAD

**Issue by callmemars1** [callmemars1/suai-teacher-info-parser#1]
## Требования
- База должна быть в 3 нормальной форме
- Должна содержать
  - ФИО преподавателя (обязательно)
  - Научная степень (обязательно)
  - Почта
  - Телефон
  - Институт
  - Кафедра
 - Информация может отсутствовать

**Comment by Nytru** [comment]
насрал

**Comment by callmemars1** [comment]
Убрал университет

**Comment by Nytru** [comment]
![image](https://user-images.githubusercontent.com/100797541/166146946-d62e16bb-0a5c-4175-9eff-9ee2d24295fd.png)

**Comment by Nytru** [comment]
и даже в 3 нормальной форме (если я не черт)

**Comment by callmemars1** [comment]
## Правочки:
- Вынеси в отдельную таблицу институты  
кафедры будут подчиненной таблицей, контакты занеси в основную
- ФИО объедини в один столбец full_name
- Переименуй таблицу Person в teachers
- Добавь в таблицу teachers должность
- Добавь в таблицу teachers столбцы с институтом и кафедрой
- Переименую scienceDegree в academic_degree для соответствия контракту (потом будет удобнее)
- Переименуй все поля в стиле snake case

**Comment by callmemars1** [comment]
И убери офис

**Comment by Nytru** [comment]
![Uploading image.png…]()

**Comment by Nytru** [comment]
![image](https://user-images.githubusercontent.com/100797541/166148753-f7570a63-b7ba-4983-9606-1bbd130992a8.png)

**Comment by Nytru** [comment]
![image](https://user-images.githubusercontent.com/100797541/166148800-3f7bfd76-63ba-490f-8631-0eca6b61e74d.png)

**Comment by Nytru** [comment]
![image](https://user-images.githubusercontent.com/100797541/166148820-1a96e2b8-349b-4339-81c9-fd32791a5ddd.png)

**Comment by Jarkness** [comment]
База не находится даже в 1ой нормальной форме (схема в принципе составлена неверно с точки зрения построения диаграмм ER или реляционных)

Ты не указал ключи (внешние, первичные).

Не указаны связи (Один к одному, много к одному и т.д.)

**Comment by Jarkness** [comment]
По поводу выбора названия для комнаты - classroom либо auditorium. Офис точно не подходит.

**Comment by callmemars1** [comment]
Таблица хранит множество записей, так что и называться она должна во множественном числе (не teacher а teachers),  
Не вынес фио в отдельный столбец,
институт с маленькой буквы должен быть, не вижу таблицы под институты и кафедру

**Comment by Nytru** [comment]
потомушто нахуй она не нужна

**Comment by Nytru** [comment]
сука

**Comment by Nytru** [comment]
с фио у тебя есть

**Comment by callmemars1** [comment]
![Image](https://user-images.githubusercontent.com/86615975/166149160-842c6a4d-686e-4b65-8762-a80b80461523.png)

вот это должно быть одной строкой

**Comment by Jarkness** [comment]
> 

Один преподаватель может относится ко многим институтам.

**Comment by Jarkness** [comment]
У одного преподавателя может быть много номеров.
У одного преподавателя может быть несколько степеней в разных науках.

**Comment by callmemars1** [comment]
Тогда контакты тоже нужно разнести по таблицам типо
```
id |  phone | teacher_id
1  | 890045 | 228
```
И так для всех контактных данных

**Comment by Jarkness** [comment]
@callmemars1, правильная мысль. Советую тебе созвонится с @Nytru и помочь ему с этой задачей. Либо я могу это сделать.

**Comment by callmemars1** [comment]
@Jarkness, @Nytru соберитесь вы, я сейчас не могу просто

**Comment by Jarkness** [comment]
@Nytru, напиши мне в вк, чтобы я дал тебе контакты.

**Comment by Nytru** [comment]
![image](https://user-images.githubusercontent.com/100797541/166238174-cee9d5ae-15c5-4366-b176-2e166e47bf04.png)
С учетом последних просьб

**Comment by callmemars1** [comment]
У тебя составной PK в class_rooms из id и building_id?

**Comment by Nytru** [comment]
Da

**Comment by callmemars1** [comment]
> Da

- А че тогда в учителе просто id

**Comment by callmemars1** [comment]
@Jarkness, чекни

**Comment by Nytru** [comment]
@LomasovEgor

**Comment by LomasovEgor** [comment]
@Nytru Ты лох

**Comment by Nytru** [comment]
@LomasovEgor you

**Comment by Nytru** [comment]
![image](https://user-images.githubusercontent.com/100797541/166686872-14f3cdd0-91d6-4954-9d41-88fcf274a22c.png)

**Comment by callmemars1** [comment]
@Nytru , @Jarkness, Я принимаю эту схему
@LomasovEgor, Начинай рисовать свою схему на базе этой ([Задача](https://github.com/callmemars1/suai-timetable-parser/issues/6)), можешь запросить исходники у @Nytru
