### ISSUE TITLE
Сделать парсер информации о преподавателях

### ISSUE THREAD

**Issue by callmemars1** [callmemars1/suai-teacher-info-parser#3]
## Требования
- Парсить информацию в бд при запуске
- Добавить проверку актуальности с помощью хешей страниц
- Парсить диапазон id преподавателей 0 - 100к
## Источник
[Пример ссылки на преподавателя](https://pro.guap.ru/exters/profile/tab1/26431)

**Comment by Nytru** [comment]
Запушил на ветку
